twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        # the value is the service's id
        users: '@App\Service\GlobalVar'

when@test:
    twig:
        strict_variables: true