version: '3'

services:
    database:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER:     main
            POSTGRES_PASSWORD: main
            POSTGRES_DB:       main
        ports: [5432]